image: maven:3-jdk-8

.default_tag: &default_tag
  tags:
    - backend

stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository/
    - target/

compile:
  stage: build
  <<: *default_tag
  script:
    - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  <<: *default_tag
  script:
    - mvn $MAVEN_CLI_OPTS clean jacoco:prepare-agent test jacoco:report
    - cat target/site/jacoco/index.html

deploy:
  stage: deploy
  <<: *default_tag
  script:
    - mvn $MAVEN_CLI_OPTS deploy -DskipTests
  only:
    - develop
